# Generated by Django 5.1.5 on 2025-01-30 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='first_name',
        ),
    ]
